services:
  - type: web
    name: smartetude
    env: python
    buildCommand: pip install -r requirements.txt && npm install && npm run build:css
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn fiches_revision.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: fiches_revision.settings
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true

