# Generated by Django 5.2.5 on 2025-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text='Résumé généré par ChatGPT avec structure et métadonnées', null=True, verbose_name='Résumé IA structuré'),
        ),
    ]
