# Generated by Django 4.2.24 on 2025-10-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billingplan_subscription_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID côté Lygos (payin_id)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operator',
            field=models.CharField(blank=True, help_text='Ex: MTN, AIRTEL_CONGO', max_length=50),
        ),
    ]
