# Generated by Django

from django.db import migrations


def create_initial_badges_and_achievements(apps, schema_editor):
    """Crée les badges et achievements initiaux pour la gamification"""
    Badge = apps.get_model('gamification', 'Badge')
    Achievement = apps.get_model('gamification', 'Achievement')
    
    # Badges initiaux
    badges_data = [
        {
            'name': 'Premier Pas',
            'description': 'Complétez votre premier quiz',
            'badge_type': 'achievement',
            'difficulty': 'bronze',
            'icon': 'fa-star',
            'color': '#CD7F32',
            'points_reward': 50,
            'criteria': {'type': 'first_quiz_completed'}
        },
        {
            'name': 'Score Parfait',
            'description': 'Obtenez 100% à un quiz',
            'badge_type': 'achievement',
            'difficulty': 'gold',
            'icon': 'fa-trophy',
            'color': '#FFD700',
            'points_reward': 200,
            'criteria': {'type': 'perfect_score', 'score': 100}
        },
        {
            'name': 'Excellent',
            'description': 'Obtenez 90% ou plus à un quiz',
            'badge_type': 'achievement',
            'difficulty': 'silver',
            'icon': 'fa-medal',
            'color': '#C0C0C0',
            'points_reward': 100,
            'criteria': {'type': 'excellent_score', 'score': 90}
        },
        {
            'name': 'Débutant Confirmé',
            'description': 'Réussissez 10 quiz',
            'badge_type': 'milestone',
            'difficulty': 'bronze',
            'icon': 'fa-certificate',
            'color': '#CD7F32',
            'points_reward': 150,
            'criteria': {'type': 'quizzes_passed', 'count': 10}
        },
        {
            'name': 'Expert',
            'description': 'Réussissez 50 quiz',
            'badge_type': 'milestone',
            'difficulty': 'silver',
            'icon': 'fa-award',
            'color': '#C0C0C0',
            'points_reward': 500,
            'criteria': {'type': 'quizzes_passed', 'count': 50}
        },
        {
            'name': 'Maître',
            'description': 'Réussissez 100 quiz',
            'badge_type': 'milestone',
            'difficulty': 'gold',
            'icon': 'fa-crown',
            'color': '#FFD700',
            'points_reward': 1000,
            'criteria': {'type': 'quizzes_passed', 'count': 100}
        },
        {
            'name': 'Sérieux',
            'description': 'Maintenez un streak de 7 jours',
            'badge_type': 'achievement',
            'difficulty': 'bronze',
            'icon': 'fa-fire',
            'color': '#CD7F32',
            'points_reward': 200,
            'criteria': {'type': 'streak', 'days': 7}
        },
        {
            'name': 'Déterminé',
            'description': 'Maintenez un streak de 30 jours',
            'badge_type': 'achievement',
            'difficulty': 'gold',
            'icon': 'fa-flame',
            'color': '#FFD700',
            'points_reward': 1000,
            'criteria': {'type': 'streak', 'days': 30}
        },
        {
            'name': 'Consistant',
            'description': 'Maintenez un score moyen de 85% ou plus',
            'badge_type': 'achievement',
            'difficulty': 'silver',
            'icon': 'fa-chart-line',
            'color': '#C0C0C0',
            'points_reward': 300,
            'criteria': {'type': 'average_score', 'score': 85}
        },
    ]
    
    # Créer les badges
    for badge_data in badges_data:
        Badge.objects.get_or_create(
            name=badge_data['name'],
            defaults={
                'description': badge_data['description'],
                'badge_type': badge_data['badge_type'],
                'difficulty': badge_data['difficulty'],
                'icon': badge_data['icon'],
                'color': badge_data['color'],
                'points_reward': badge_data['points_reward'],
                'criteria': badge_data['criteria'],
                'is_active': True,
                'is_hidden': False
            }
        )
    
    # Achievements initiaux
    achievements_data = [
        {
            'name': 'Premier Quiz',
            'description': 'Complétez votre premier quiz',
            'achievement_type': 'quiz_performance',
            'threshold': 1,
            'experience_points': 50,
            'icon': 'fa-play-circle',
            'color': '#3B82F6'
        },
        {
            'name': 'Débutant',
            'description': 'Réussissez 5 quiz',
            'achievement_type': 'quiz_performance',
            'threshold': 5,
            'experience_points': 100,
            'icon': 'fa-graduation-cap',
            'color': '#10B981'
        },
        {
            'name': 'Confirmé',
            'description': 'Réussissez 25 quiz',
            'achievement_type': 'quiz_performance',
            'threshold': 25,
            'experience_points': 500,
            'icon': 'fa-certificate',
            'color': '#F59E0B'
        },
        {
            'name': 'Expert',
            'description': 'Réussissez 50 quiz',
            'achievement_type': 'quiz_performance',
            'threshold': 50,
            'experience_points': 1000,
            'icon': 'fa-award',
            'color': '#8B5CF6'
        },
        {
            'name': 'Maître',
            'description': 'Réussissez 100 quiz',
            'achievement_type': 'quiz_performance',
            'threshold': 100,
            'experience_points': 2500,
            'icon': 'fa-crown',
            'color': '#EF4444'
        },
        {
            'name': 'Maîtrise Basique',
            'description': 'Obtenez un score moyen de 70%',
            'achievement_type': 'mastery',
            'threshold': 70,
            'experience_points': 200,
            'icon': 'fa-star',
            'color': '#3B82F6'
        },
        {
            'name': 'Maîtrise Avancée',
            'description': 'Obtenez un score moyen de 85%',
            'achievement_type': 'mastery',
            'threshold': 85,
            'experience_points': 500,
            'icon': 'fa-star-half-alt',
            'color': '#10B981'
        },
        {
            'name': 'Maîtrise Parfaite',
            'description': 'Obtenez un score moyen de 95%',
            'achievement_type': 'mastery',
            'threshold': 95,
            'experience_points': 1500,
            'icon': 'fa-star',
            'color': '#F59E0B'
        },
        {
            'name': 'Série de 3',
            'description': 'Maintenez un streak de 3 jours',
            'achievement_type': 'streak',
            'threshold': 3,
            'experience_points': 100,
            'icon': 'fa-fire',
            'color': '#EF4444'
        },
        {
            'name': 'Série de 7',
            'description': 'Maintenez un streak de 7 jours',
            'achievement_type': 'streak',
            'threshold': 7,
            'experience_points': 300,
            'icon': 'fa-fire',
            'color': '#F59E0B'
        },
        {
            'name': 'Série de 30',
            'description': 'Maintenez un streak de 30 jours',
            'achievement_type': 'streak',
            'threshold': 30,
            'experience_points': 2000,
            'icon': 'fa-flame',
            'color': '#EF4444'
        },
    ]
    
    # Créer les achievements
    for achievement_data in achievements_data:
        Achievement.objects.get_or_create(
            name=achievement_data['name'],
            defaults={
                'description': achievement_data['description'],
                'achievement_type': achievement_data['achievement_type'],
                'threshold': achievement_data['threshold'],
                'experience_points': achievement_data['experience_points'],
                'icon': achievement_data['icon'],
                'color': achievement_data['color'],
                'is_active': True
            }
        )


def reverse_migration(apps, schema_editor):
    """Supprime les badges et achievements créés"""
    Badge = apps.get_model('gamification', 'Badge')
    Achievement = apps.get_model('gamification', 'Achievement')
    
    badge_names = [
        'Premier Pas', 'Score Parfait', 'Excellent', 'Débutant Confirmé',
        'Expert', 'Maître', 'Sérieux', 'Déterminé', 'Consistant'
    ]
    
    achievement_names = [
        'Premier Quiz', 'Débutant', 'Confirmé', 'Expert', 'Maître',
        'Maîtrise Basique', 'Maîtrise Avancée', 'Maîtrise Parfaite',
        'Série de 3', 'Série de 7', 'Série de 30'
    ]
    
    Badge.objects.filter(name__in=badge_names).delete()
    Achievement.objects.filter(name__in=achievement_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_badges_and_achievements,
            reverse_migration
        ),
    ]
